### ISSUE TITLE
Failed parsing with bloodType

### ISSUE THREAD

**Issue by laPeregrin** [saul/demofile-net#63]
### Research

- [X] I've already searched and I could not find an existing issue or discussion about this issue.

### Description

System.NotSupportedException: Unrecognised serializer field: m_nBloodType
   at DemoFile.Sdk.CEntityInstance.CreateFieldDecoder(SerializableField field, DecoderSet decoderSet)
   at DemoFile.Sdk.CBaseEntity.CreateFieldDecoder(SerializableField field, DecoderSet decoderSet)
   at DemoFile.Sdk.CBaseModelEntity.CreateFieldDecoder(SerializableField field, DecoderSet decoderSet)
   at DemoFile.Sdk.CBaseAnimGraph.CreateFieldDecoder(SerializableField field, DecoderSet decoderSet)
   at DemoFile.Sdk.CEconEntity.CreateFieldDecoder(SerializableField field, DecoderSet decoderSet)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at DemoFile.Sdk.DecoderSet.CreateDecoder[T](SerializerKey serializerKey)
   at DemoFile.Sdk.DecoderSet.GetDecoder[T](SerializerKey serializerKey)
   at DemoFile.Sdk.DecoderSet.TryGetDecoder(String className, Type& classType, SendNodeDecoder`1& decoder)
   at DemoFile.DemoParser.OnDemoClassInfo(CDemoClassInfo msg)
   at DemoFile.DemoEvents.ReadDemoCommandCore[T](Action`1 callback, MessageParser`1 parser, ReadOnlySpan`1 buffer, Boolean isCompressed)
   at DemoFile.DemoEvents.ReadDemoCommand(EDemoCommands msgType, ReadOnlySpan`1 buffer, Boolean isCompressed)
   at DemoFile.DemoParser.MoveNextCoreAsync(EDemoCommands msgType, Boolean isCompressed, Int32 size, CancellationToken cancellationToken)
   at DemoFile.DemoParser.StartReadingAsync(Stream stream, CancellationToken cancellationToken)
   at DemoFile.DemoParser.ReadAllAsync(Stream stream, CancellationToken cancellationToken)

### Affected demos

http://replay189.valve.net/730/003686249481730261055_0831476125.dem.bz2

**Comment by xGuysOG** [comment]
likely the new update broke demos again @saul ?

**Comment by saul** [comment]
Thanks for reporting. A fix has been released as 0.14.1

**Comment by laPeregrin** [comment]
> Thanks for reporting. A fix has been released as 0.14.1

Thanks for your supporting!
