### ISSUE TITLE
CSoundEventPathCornerEntity failed to parse

### ISSUE THREAD

**Issue by laPeregrin** [saul/demofile-net#69]
### Research

- [X] I've already searched and I could not find an existing issue or discussion about this issue.

### Description

System.Exception: Attempted to create unknown entity: CSoundEventPathCornerEntity
   at DemoFile.DemoParser.<>c__DisplayClass115_0.<OnDemoClassInfo>b__1(EntityContext context)
   at DemoFile.DemoParser.OnPacketEntities(CSVCMsg_PacketEntities msg)
   at DemoFile.PacketEvents.ParseNetMessage(Int32 msgType, ReadOnlySpan`1 buf)
   at DemoFile.DemoParser.OnDemoPacket(CDemoPacket msg)
   at DemoFile.DemoEvents.ReadDemoCommand(EDemoCommands msgType, ReadOnlySpan`1 buffer, Boolean isCompressed)
   at DemoFile.DemoParser.MoveNextCoreAsync(EDemoCommands msgType, Boolean isCompressed, Int32 size, CancellationToken cancellationToken)
   at DemoFile.DemoParser.ReadAllAsync(Stream stream, CancellationToken cancellationToken)****

### Affected demos

http://replay186.valve.net/730/003688111663585689781_1784675935.dem.bz2

**Comment by saul** [comment]
A fix was released as v0.15.1 - please update and try again
