### ISSUE TITLE
Seeking fails for some demos

### ISSUE THREAD

**Issue by in0finite** [saul/demofile-net#72]
### Research

- [X] I've already searched and I could not find an existing issue or discussion about this issue.

### Description

In the specified demo, seeking fails when trying to seek past the tick 192001, with error:
```
Unhandled exception. DemoFile.InvalidDemoException: Could not find DemFullPacket at tick 192001
   at DemoFile.DemoParser.SkipToFullPacketTickAsync(DemoTick targetTick, CancellationToken cancellationToken) in demofile-net\src\DemoFile\DemoParser.FullPacket.cs:line 145
   at DemoFile.DemoParser.SeekToTickAsync(DemoTick targetTick, CancellationToken cancellationToken) in demofile-net\src\DemoFile\DemoParser.FullPacket.cs:line 97
   at Program.Main(String[] args) in demofile-net\examples\DemoFile.Example.Basic\Program.cs:line 155
   at Program.<Main>(String[] args)
```

### Code to reproduce

```csharp
var stream = new MemoryStream(File.ReadAllBytes(path));

await demo.StartReadingAsync(stream, default);

await demo.SeekToTickAsync(new DemoTick(192000), default); // works for anything below 192001

Console.WriteLine($"seeked to tick {demo.CurrentDemoTick.Value}");

await demo.SeekToTickAsync(new DemoTick(193000), default); // fails

Console.WriteLine($"seeked to tick {demo.CurrentDemoTick.Value}");
```

### Affected demos

https://www.hltv.org/matches/2372034/mouz-nxt-vs-space-cct-season-2-europe-series-3

map : Vertigo

Also happens on some recent Matchmaking demos.

**Comment by saul** [comment]
This is fixed in v0.16.1. Thanks for reporting
