### ISSUE TITLE
Support new field m_PredictedDamageTags

### ISSUE THREAD

**Issue by makhorin** [saul/demofile-net#82]
### Research

- [X] I've already searched and I could not find an existing issue or discussion about this issue.

### Description

Looks like there is new field which is not supported by decoders. Please, look at the attached demo

### Affected demos

[broken_demo.zip](https://github.com/user-attachments/files/16625944/broken_demo.zip)

**Comment by laPeregrin** [comment]
same exception: 

System.NotSupportedException: Unrecognised serializer field: m_PredictedDamageTags
   at DemoFile.Sdk.CEntityInstance.CreateFieldDecoder(SerializableField field, DecoderSet decoderSet)
   at DemoFile.Sdk.CBaseEntity.CreateFieldDecoder(SerializableField field, DecoderSet decoderSet)
   at DemoFile.Sdk.CBaseModelEntity.CreateFieldDecoder(SerializableField field, DecoderSet decoderSet)
   at DemoFile.Sdk.CBaseAnimGraph.CreateFieldDecoder(SerializableField field, DecoderSet decoderSet)
   at DemoFile.Sdk.CBasePlayerPawn.CreateFieldDecoder(SerializableField field, DecoderSet decoderSet)
   at DemoFile.Sdk.CCSPlayerPawnBase.CreateFieldDecoder(SerializableField field, DecoderSet decoderSet)
   at DemoFile.Sdk.CCSPlayerPawn.CreateFieldDecoder(SerializableField field, DecoderSet decoderSet)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at DemoFile.Sdk.DecoderSet.CreateDecoder[T](SerializerKey serializerKey)
   at DemoFile.Sdk.DecoderSet.GetDecoder[T](SerializerKey serializerKey)
   at DemoFile.Sdk.DecoderSet.TryGetDecoder(String className, Type& classType, SendNodeDecoder`1& decoder)
   at DemoFile.Sdk.DecoderSet.GetDecoder(String className)
   at DemoFile.DemoParser.OnDemoClassInfo(CDemoClassInfo msg)
   at DemoFile.DemoEvents.ReadDemoCommand(EDemoCommands msgType, ReadOnlySpan`1 buffer, Boolean isCompressed)
   at DemoFile.DemoParser.MoveNextCoreAsync(EDemoCommands msgType, Boolean isCompressed, Int32 size, CancellationToken cancellationToken)
   at DemoFile.DemoParser.StartReadingAsync(Stream stream, CancellationToken cancellationToken)
   at DemoFile.DemoParser.ReadAllAsync(Stream stream, CancellationToken cancellationToken)
   at Questera.CsGo.Parser.Parser.ParseAsync(String fileName) in /src/CsGoProvider/Questera.CsGo.Parser/Parser.cs:line 59

**Comment by saul** [comment]
The fix will shortly be released as v0.18.1

Thank you for reporting
